### ISSUE TITLE
Doubt on this model

### ISSUE THREAD

**Issue by dcorrea777** [alexishevia/blogExamples#2]
Hi,

I found your article very interesting, but when you have an application that has many endpoint this can not be a problem in memory consumption?

**Comment by alexishevia** [comment]
Hey @danilosilva87, I have a couple different examples on this repo, one per branch. Could you be more specific about which article/code you're referring to?

**Comment by dcorrea777** [comment]
Hello @alexishevia  thanks for replying = D
In fact I made a mess between the articles, however a friend referred his article as a solution to their problem. [that](https://commandz.io/post/serverless/2017-10-14-serverless-express-API-lambda-boilerplate/)

In the article he wrote, he says the problem is in the amount of resources used by aws. (There seems to be a limitation) [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)

In this paragraph he says he found the solution in his post
> Fortunately, I had found this article earlier on Medium and I saw a way to define innumerable API endpoints without surpassing the Cloudformation Template limit. So I put together a boilerplate repo that our team could base their work off of and it worked splendidly.

I wanted to know of you, set an endpoint like this example below can not there be some problem in memory consumption?
```
handler: index.handler
    events:
        - http: ANY /
        - http: 'ANY {proxy +}'
```
Sorry for bothering, this doubt was for the other friend, but you answered me first, it costs nothing to ask = D

**Comment by alexishevia** [comment]
@danilosilva87 loading a complete express application would in fact consume more memory than loading a single handler. However, I don't think memory consumption should be a concern, even with a big express application (assuming you're only loading code into memory and not data files).

However, if you have a big express app being served by a single handler you might incur in a performance penalty during startup, since lambda has to `require` your entire app and parse it before being able to handle the request.

I would recommend measuring how your app is performing, and if you do find an issue - breaking down your app into smaller parts. However, I have not run into this issue personally.

**Comment by dcorrea777** [comment]
Many thanks for the answer, clarified many doubts that I had.
